# Since the Travis CI environment http://docs.travis-ci.com/user/ci-environment/
# provides GNU GCC 4.6, which does not support -std=c++11 GNU GCC 4.8 is installed

# NOTE: Please validate this file after editing it using
#       Travis WebLint http://lint.travis-ci.org/
#       or travis-yaml https://github.com/travis-ci/travis-yaml

language: cpp
compiler:
  - clang
  - gcc

before_install:
    # Add software package repositories with recent versions of gcc and boost
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test --yes
  - sudo add-apt-repository ppa:boost-latest/ppa --yes
  - sudo apt-get update -qq

install: 
    # Install GNU GCC 4.8 required by use of C++11
  - sudo apt-get install -qq g++-4.8 gcc-4.8
  - export CXX="g++-4.8" CC="gcc-4.8"
    # Install Ledger dependencies
  - sudo apt-get install -qq libboost1.55 libgmp-dev libmpfr-dev libeditline-dev

before_script:
  - export JOBS=2
  - ./acprep opt make --jobs $JOBS --python

script:
  - ./acprep check --jobs $JOBS -- --output-on-failure
  - PYTHONPATH=. python python/demo.py

notifications:
  email:
    on_success: change
    on_failure: change
  irc:
    channels: [ "chat.freenode.net#ledger" ]
    on_success: change
    on_failure: change
